name: CI
# Deployment patterned after https://medium.com/@michaelekpang/creating-a-ci-cd-pipeline-using-github-actions-b65bb248edfe

on:
  pull_request:
    branches:
      - '*'


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Add Heroku credentials
        run: |
          echo "machine api.heroku.com" > ~/.netrc
          echo "  login penny.university.mod@gmail.com" >> ~/.netrc
          echo "  password ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc
          echo "machine git.heroku.com" >> ~/.netrc
          echo "  login penny.university.mod@gmail.com" >> ~/.netrc
          echo "  password ${{ secrets.HEROKU_API_KEY }}" >> ~/.netrc
      - name: Backup DB
        run: heroku pg:backups:capture -a penny-university
      - name: Push
        run: |
          echo "NOTE: if this suddenly breaks, it might be because of an expired API key"
          git remote add heroku https://git.heroku.com/penny-stage.git  #TODO! change
          git push heroku HEAD:master -f
