name: CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  test-backend:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v1
    - run: |
        script/message_to_slack ${{ secrets.SLACK_API_KEY }} "test $(date)"
        echo $SLACK_API_KEY | cut -c52-
