name: CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  test-backend:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v1
    - name: this fails
      run: |
        script/message_to_slack ${{ secrets.SLACK_API_KEY }} "success"
    - name: alert if failed
      if: ${{ failure() }}
      run: script/message_to_slack ${{ secrets.SLACK_API_KEY }} "failure"
